unset CPATH
unset LD_LIBRARY_PATH
unset LIBRARY_PATH
unset MANPATH
[ -z ${CPATH_OLD+x} ] || CPATH=$CPATH_OLD
[ -z ${LD_LIBRARY_PATH_OLD+x} ] || LIBRARY_PATH=$LD_LIBRARY_PATH_OLD
[ -z ${LIBRARY_PATH_OLD+x} ] || LIBRARY_PATH=$LIBRARY_PATH_OLD
[ -z ${MANPATH_OLD+x} ] || MANPATH=$MANPATH_OLD
