[ -z ${CPATH+x} ] || CPATH_OLD=$CPATH
[ -z ${LD_LIBRARY_PATH+x} ] || LIBRARY_PATH_OLD=$LD_LIBRARY_PATH
[ -z ${LIBRARY_PATH+x} ] || LIBRARY_PATH_OLD=$LIBRARY_PATH
[ -z ${MANPATH+x} ] || MANPATH_OLD=$MANPATH
export CPATH="$CONDA_PREFIX/include"
export LD_LIBRARY_PATH="$CONDA_PREFIX/lib64:$CONDA_PREFIX/lib"
export LIBRARY_PATH="$CONDA_PREFIX/lib64:$CONDA_PREFIX/lib"
export MANPATH="$CONDA_PREFIX/share/man"
